name: 'Guardian'
description: 'Run Microsoft Guardian security analysis.'
author: 'Microsoft'
branding:
  icon: 'shield'
  color: 'black'
inputs:
  version:
    description: 'The version of Guardian to use. Default: latest'
  license:
    description: 'The license for Guardian. This must be kept as a secret in the GitHub repository.'
runs:
  using: 'node12'
  main: 'lib/action.js'