# guardian-github action sample

name: MSCA windows-latest
on:
  push:
    branches:
      - master

jobs:
  sample:
    name: Security Code Analysis

    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: windows-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

      # Install dotnet, used by OSSAR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'

      # Run open source static analysis tools
    - name: Run Microsoft Security Code Analysis
      uses: Microsoft/security-code-analysis-action@master
      id: msca

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.msca.outputs.sarifFile }}
