# guardian-github action sample

name: Microsoft Security Code Analysis Action Sample
on:
  push:
    branches:
      - master
      - test

jobs:
  sample:
    name: Self test
    runs-on: [self-hosted]
    steps:
    - name: Run Microsoft Security Code Analysis
      uses: Microsoft/security-code-analysis-action@master